#exec i3
exec sxhkd &
export DESKTOP_SESSION=plasma 
exec setxkbmap -option caps:escape &
exec copyq &
#exec startxfce4
exec startplasma-x11
#picom &
#xrandr --output LVDS-1 --primary --mode 1366x768 --pos 1440x132 --rotate normal --output VGA-1 --mode 1440x900 --pos 0x0 --rotate normal --output HDMI-1 --off --output DP-1 --off --output HDMI-2 --off --output HDMI-3 --off --output DP-2 --off --output DP-3 --off &
